default_install_hook_types:
  - pre-commit
  - commit-msg
minimum_pre_commit_version: 3.2.0

repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-fmt

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go
        entry: golangci-lint run --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false

      - id: golangci-lint-config-verify
        name: golangci-lint-config-verify
        description: Verifies the configuration file
        entry: golangci-lint config verify
        files: '\.golangci\.(?:yml|yaml|toml|json)'
        language: golang
        pass_filenames: false