package handler

import (
	"bytes"
	"encoding/json"
	"html/template"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
	"testing/fstest"
	"time"

	"github.com/wbollock/alertmanager-route-tester/internal/alertmanager"
)

// loadTemplates parses the real templates relative to the package directory so
// tests exercise the same template files that production uses.
func loadTemplates(t *testing.T) *template.Template {
	t.Helper()
	funcMap := template.FuncMap{
		"json": func(v interface{}) template.JS {
			b, _ := json.Marshal(v)
			return template.JS(b) // #nosec G203 -- the value is generated by json.Marshal before insertion.
		},
	}
	tmpl, err := template.New("").Funcs(funcMap).ParseGlob("../../templates/*.html")
	if err != nil {
		t.Fatalf("failed to parse templates: %v", err)
	}
	return tmpl
}

// resultData mirrors the anonymous struct passed to result.html in HandleTest.
type resultData struct {
	Receiver                 string
	ReceiverConfig           *alertmanager.Receiver
	MatchedRoutes            []alertmanager.MatchedRoute
	MatchedReceivers         []string
	RouteSteps               []RouteStep
	ContinueCount            int
	FinalMatch               MatchSummary
	DefaultRoot              bool
	MatchedReceiverSummaries []ReceiverSummary
	Labels                   map[string]string
	Error                    string
}

func TestNewWithClientsFromFSLoadsTemplatesWithoutWorkingDirectory(t *testing.T) {
	templateFS := fstest.MapFS{
		"templates/index.html":  &fstest.MapFile{Data: []byte("{{define \"index.html\"}}index{{end}}")},
		"templates/result.html": &fstest.MapFile{Data: []byte("{{define \"result.html\"}}result{{end}}")},
	}

	h := NewWithClientsFromFS(nil, nil, "", templateFS)
	if h == nil || h.tmpl == nil {
		t.Fatal("NewWithClientsFromFS() returned a handler without templates")
	}
}

func TestIndexTemplateLabelsCachedConfig(t *testing.T) {
	tmpl := loadTemplates(t)
	data := struct {
		LabelSuggestions     []alertmanager.LabelSuggestion
		SampleAlerts         []alertmanager.SampleAlert
		Config               *alertmanager.Config
		AlertmanagerURL      string
		AlertmanagerNames    []string
		SelectedAlertmanager string
		ConnectionStatus     bool
		ConnectionError      string
		ConfigCachedAt       time.Time
		ConfigWasCached      bool
	}{
		AlertmanagerURL:  "http://localhost:9093",
		ConnectionStatus: true,
		ConfigCachedAt:   time.Now(),
		ConfigWasCached:  true,
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "index.html", data); err != nil {
		t.Fatalf("index.html failed to render: %v", err)
	}
	output := buf.String()
	if !strings.Contains(output, "Using cached configuration") {
		t.Fatal("cached config status is missing")
	}
	if !strings.Contains(output, "config-reload-error") || !strings.Contains(output, "Reload failed. Using cached configuration.") {
		t.Fatal("reload error feedback is missing")
	}
}

func TestHandleTestRejectsOversizedJSON(t *testing.T) {
	body := []byte(`{"labels":{"label":"` + strings.Repeat("x", int(maxTestRequestBodyBytes)) + `"}}`)
	request := httptest.NewRequest(http.MethodPost, "/test", bytes.NewReader(body))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	(&Handler{}).HandleTest(response, request)

	if response.Code != http.StatusRequestEntityTooLarge {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusRequestEntityTooLarge)
	}
}

func TestHandleTestRejectsOversizedJSONAfterFirstValue(t *testing.T) {
	body := []byte(`{"labels":{}}` + strings.Repeat(" ", int(maxTestRequestBodyBytes)))
	request := httptest.NewRequest(http.MethodPost, "/test", bytes.NewReader(body))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	(&Handler{}).HandleTest(response, request)

	if response.Code != http.StatusRequestEntityTooLarge {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusRequestEntityTooLarge)
	}
}

func TestHandleTestRejectsTrailingJSONValue(t *testing.T) {
	request := httptest.NewRequest(http.MethodPost, "/test", strings.NewReader(`{"labels":{}} {}`))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	(&Handler{}).HandleTest(response, request)

	if response.Code != http.StatusBadRequest || !strings.Contains(response.Body.String(), "Invalid JSON") {
		t.Fatalf("response = %d %q, want invalid JSON response", response.Code, response.Body.String())
	}
}

func TestHandleTestRejectsOversizedForm(t *testing.T) {
	body := strings.Repeat("label=x&", int(maxTestRequestBodyBytes/7)+1)
	request := httptest.NewRequest(http.MethodPost, "/test", strings.NewReader(body))
	request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	response := httptest.NewRecorder()

	(&Handler{}).HandleTest(response, request)

	if response.Code != http.StatusRequestEntityTooLarge {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusRequestEntityTooLarge)
	}
}

func TestHandleTestUsesSelectedAlertmanager(t *testing.T) {
	server := func(t *testing.T, receiver string) *httptest.Server {
		t.Helper()
		return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: ` + receiver + `\nreceivers:\n- name: ` + receiver + `\n"}}`))
		}))
	}
	production := server(t, "production-default")
	defer production.Close()
	staging := server(t, "staging-default")
	defer staging.Close()

	h := &Handler{
		clients: map[string]*alertmanager.Client{
			"production": alertmanager.NewClient(production.URL, false),
			"staging":    alertmanager.NewClient(staging.URL, false),
		},
		alertmanagerNames:   []string{"production", "staging"},
		defaultAlertmanager: "production",
		tmpl:                loadTemplates(t),
	}
	request := httptest.NewRequest(http.MethodPost, "/test?alertmanager=staging", bytes.NewBufferString(`{"labels":{"alertname":"Test"}}`))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	h.HandleTest(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, body = %s", response.Code, response.Body.String())
	}
	var result TestResponse
	if err := json.Unmarshal(response.Body.Bytes(), &result); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if result.Receiver != "staging-default" {
		t.Fatalf("receiver = %q, want staging-default", result.Receiver)
	}
}

func TestHandleTestUsesSelectedAlertmanagerFromForm(t *testing.T) {
	server := func(t *testing.T, receiver string) *httptest.Server {
		t.Helper()
		return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: ` + receiver + `\nreceivers:\n- name: ` + receiver + `\n"}}`))
		}))
	}
	production := server(t, "production-default")
	defer production.Close()
	staging := server(t, "staging-default")
	defer staging.Close()

	h := &Handler{
		clients: map[string]*alertmanager.Client{
			"production": alertmanager.NewClient(production.URL, false),
			"staging":    alertmanager.NewClient(staging.URL, false),
		},
		alertmanagerNames:   []string{"production", "staging"},
		defaultAlertmanager: "production",
		tmpl:                loadTemplates(t),
	}
	form := url.Values{
		"alertmanager": {"staging"},
		"alertname":    {"Test"},
	}
	request := httptest.NewRequest(http.MethodPost, "/test", strings.NewReader(form.Encode()))
	request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	response := httptest.NewRecorder()

	h.HandleTest(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, body = %s", response.Code, response.Body.String())
	}
	var result TestResponse
	if err := json.Unmarshal(response.Body.Bytes(), &result); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if result.Receiver != "staging-default" {
		t.Fatalf("receiver = %q, want staging-default", result.Receiver)
	}
}

func TestHandleIndexRejectsUnknownAlertmanager(t *testing.T) {
	tmpl := loadTemplates(t)
	h := &Handler{
		clients:             map[string]*alertmanager.Client{"production": alertmanager.NewClient("http://127.0.0.1:1", false)},
		alertmanagerNames:   []string{"production"},
		defaultAlertmanager: "production",
		tmpl:                tmpl,
	}
	response := httptest.NewRecorder()

	h.HandleIndex(response, httptest.NewRequest(http.MethodGet, "/?alertmanager=missing", http.NoBody))

	body := response.Body.String()
	if response.Code != http.StatusOK || !strings.Contains(body, "unknown Alertmanager") || !strings.Contains(body, "missing") {
		t.Fatalf("response = %d %q, want unknown Alertmanager error", response.Code, body)
	}
	if !strings.Contains(body, "http://127.0.0.1:1") || !strings.Contains(body, `name="alertmanager" value="production"`) {
		t.Fatalf("response = %q, want default Alertmanager connection state", body)
	}
}

func TestHandleConfigLabelsRejectsNonGetRequests(t *testing.T) {
	h := &Handler{}
	request := httptest.NewRequest(http.MethodPost, "/config/labels", http.NoBody)
	response := httptest.NewRecorder()

	h.HandleConfigLabels(response, request)

	if response.Code != http.StatusMethodNotAllowed {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusMethodNotAllowed)
	}
}

func TestHandleIndexShowsCachedStatusAfterInitialLoad(t *testing.T) {
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\nreceivers:\n- name: default\n"}}`))
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false), tmpl: loadTemplates(t)}
	first := httptest.NewRecorder()
	h.HandleIndex(first, httptest.NewRequest(http.MethodGet, "/", http.NoBody))
	if first.Code != http.StatusOK || !strings.Contains(first.Body.String(), "Connected to") {
		t.Fatalf("first response = %d %q, want live connection status", first.Code, first.Body.String())
	}

	second := httptest.NewRecorder()
	h.HandleIndex(second, httptest.NewRequest(http.MethodGet, "/", http.NoBody))
	if second.Code != http.StatusOK || !strings.Contains(second.Body.String(), "Using cached configuration") {
		t.Fatalf("second response = %d %q, want cached status", second.Code, second.Body.String())
	}
	if requests != 1 {
		t.Fatalf("Alertmanager requests = %d, want one cached read", requests)
	}
}

func TestBuildRouteSummaryTreatsNestedParentAsTraceOnly(t *testing.T) {
	config := &alertmanager.Config{
		Receivers: []alertmanager.Receiver{
			{Name: "team-database"},
			{Name: "pagerduty-database"},
		},
	}
	matched := []alertmanager.MatchedRoute{
		{Route: &alertmanager.Route{Receiver: "team-database"}},
		{Route: &alertmanager.Route{Receiver: "pagerduty-database"}, Depth: 1, IsSubroute: true, IsEffective: true, ResolvedReceiver: "pagerduty-database"},
	}

	steps, receivers, continueCount, _ := buildRouteSummary(matched, "pagerduty-database", config)
	if got := strings.Join(receivers, ","); got != "pagerduty-database" {
		t.Fatalf("matched receivers = %q, want pagerduty-database", got)
	}
	if continueCount != 0 {
		t.Fatalf("continue count = %d, want 0", continueCount)
	}
	if len(steps) != 2 || steps[0].IsFinal || !steps[1].IsFinal {
		t.Fatalf("route steps = %#v, want only child final", steps)
	}

	summaries := buildReceiverSummaries(matched, "pagerduty-database", config)
	if len(summaries) != 1 || summaries[0].Name != "pagerduty-database" {
		t.Fatalf("receiver summaries = %#v, want only pagerduty-database", summaries)
	}
}

func TestIsDefaultRootRejectsEffectiveTopLevelMatch(t *testing.T) {
	config := &alertmanager.Config{Route: &alertmanager.Route{Receiver: "default"}}
	matched := []alertmanager.MatchedRoute{{Route: &alertmanager.Route{Match: map[string]string{"component": "infrastructure"}}, IsEffective: true, ResolvedReceiver: "default"}}

	if isDefaultRoot("default", matched, config) {
		t.Fatal("isDefaultRoot() = true, want false for an effective route match")
	}
}

func TestIsDefaultRootRejectsEffectiveNestedMatchUsingRootReceiver(t *testing.T) {
	config := &alertmanager.Config{Route: &alertmanager.Route{Receiver: "default"}}
	matched := []alertmanager.MatchedRoute{
		{Route: &alertmanager.Route{}, Depth: 0, ResolvedReceiver: "default"},
		{Route: &alertmanager.Route{}, Depth: 1, IsEffective: true, ResolvedReceiver: "default"},
	}

	if isDefaultRoot("default", matched, config) {
		t.Fatal("isDefaultRoot() = true, want false for an effective nested match")
	}
}

// TestHandleTestRendersErrorForMissingRootRoute verifies that a missing root
// route returns a rendered error response instead of attempting route matching.
func TestHandleTestRendersErrorForMissingRootRoute(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/api/v2/status" {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"receivers:\n  - name: default\n"}}`))
	}))
	defer server.Close()

	h := &Handler{
		client: alertmanager.NewClient(server.URL, false),
		tmpl:   loadTemplates(t),
	}
	request := httptest.NewRequest(http.MethodPost, "/test", bytes.NewBufferString(`{"labels":{"alertname":"MissingRoute"}}`))
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("HX-Request", "true")
	response := httptest.NewRecorder()

	h.HandleTest(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	if !bytes.Contains(response.Body.Bytes(), []byte("no route defined")) {
		t.Fatalf("response = %q, want missing-route error", response.Body.String())
	}
}

func TestReloadConfigRefetchesConfig(t *testing.T) {
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/api/v2/status" {
			http.NotFound(w, r)
			return
		}
		requests++
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\nreceivers:\n  - name: default\n"}}`))
	}))
	defer server.Close()

	client := alertmanager.NewClient(server.URL, false)
	h := &Handler{client: client}
	req := httptest.NewRequest(http.MethodPost, "/config/reload", nil)
	response := httptest.NewRecorder()

	h.HandleReloadConfig(response, req)

	if response.Code != http.StatusSeeOther {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusSeeOther)
	}
	if requests != 1 {
		t.Fatalf("status requests after reload = %d, want 1", requests)
	}
	if client.ConfigCachedAt().IsZero() {
		t.Fatal("expected config to be cached after reload")
	}
	config, err := client.GetConfig()
	if err != nil {
		t.Fatalf("cached GetConfig() error = %v", err)
	}
	if config.Route == nil || config.Route.Receiver != "default" {
		t.Fatalf("cached route = %#v, want default root route", config.Route)
	}
	if requests != 1 {
		t.Fatalf("status requests after cache hit = %d, want 1", requests)
	}

	client.InvalidateConfig()
	if _, err := client.GetConfig(); err != nil {
		t.Fatalf("GetConfig() after invalidation error = %v", err)
	}
	if requests != 2 {
		t.Fatalf("status requests after invalidation = %d, want 2", requests)
	}
}

func TestReloadConfigReturnsFailureWhenFetchFails(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false)}
	request := httptest.NewRequest(http.MethodPost, "/config/reload", nil)
	response := httptest.NewRecorder()

	h.HandleReloadConfig(response, request)

	if response.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusServiceUnavailable)
	}
}

func TestReloadConfigReturnsHXErrorTriggerWhenFetchFails(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false)}
	request := httptest.NewRequest(http.MethodPost, "/config/reload", http.NoBody)
	request.Header.Set("HX-Request", "true")
	response := httptest.NewRecorder()

	h.HandleReloadConfig(response, request)

	if response.Code != http.StatusNoContent {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusNoContent)
	}
	if got := response.Header().Get("HX-Trigger"); got != "config-reload-error" {
		t.Fatalf("HX-Trigger = %q, want config-reload-error", got)
	}
}

func TestReloadConfigPreservesCachedConfigWhenRefreshFails(t *testing.T) {
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if requests == 1 {
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\nreceivers:\n  - name: default\n"}}`))
			return
		}
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer server.Close()

	client := alertmanager.NewClient(server.URL, false)
	if _, err := client.GetConfig(); err != nil {
		t.Fatalf("initial GetConfig() error = %v", err)
	}

	h := &Handler{client: client}
	request := httptest.NewRequest(http.MethodPost, "/config/reload", nil)
	response := httptest.NewRecorder()
	h.HandleReloadConfig(response, request)

	if response.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusServiceUnavailable)
	}
	config, err := client.GetConfig()
	if err != nil {
		t.Fatalf("cached GetConfig() error = %v", err)
	}
	if config.Route == nil || config.Route.Receiver != "default" {
		t.Fatalf("cached route = %#v, want default", config.Route)
	}
	if requests != 2 {
		t.Fatalf("status requests = %d, want 2", requests)
	}
}

func TestReloadConfigReturnsHXRefreshAfterSuccess(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\nreceivers:\n  - name: default\n"}}`))
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false)}
	request := httptest.NewRequest(http.MethodPost, "/config/reload", nil)
	request.Header.Set("HX-Request", "true")
	response := httptest.NewRecorder()

	h.HandleReloadConfig(response, request)

	if response.Code != http.StatusNoContent {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusNoContent)
	}
	if got := response.Header().Get("HX-Refresh"); got != "true" {
		t.Fatalf("HX-Refresh = %q, want true", got)
	}
}

func TestResultTemplateRendersRootFallbackWithMatchedParent(t *testing.T) {
	tmpl := loadTemplates(t)
	data := resultData{
		Receiver:         "default",
		MatchedRoutes:    []alertmanager.MatchedRoute{{Route: &alertmanager.Route{Match: map[string]string{"component": "infrastructure"}}, IsEffective: true, ResolvedReceiver: "default"}},
		MatchedReceivers: []string{"default"},
		DefaultRoot:      false,
		Labels:           map[string]string{"component": "infrastructure"},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "result.html", data); err != nil {
		t.Fatalf("result.html failed to render root fallback: %v", err)
	}
	output := buf.String()
	if strings.Contains(output, "root route's receiver") {
		t.Fatal("effective route match should not show the root fallback notice")
	}
	if !strings.Contains(output, "Matched route rules") {
		t.Fatal("effective route match should show the matched route")
	}
}

func TestHandleTestReturnsNestedRouteJSON(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\n  routes:\n  - match:\n      team: database\n    receiver: team-database\n    routes:\n    - match:\n        severity: critical\n      receiver: pagerduty-database\nreceivers:\n- name: default\n- name: team-database\n- name: pagerduty-database\n"}}`))
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false)}
	request := httptest.NewRequest(http.MethodPost, "/test", bytes.NewBufferString(`{"labels":{"team":"database","severity":"critical"}}`))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	h.HandleTest(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	var body struct {
		Receiver      string                      `json:"receiver"`
		MatchedRoutes []alertmanager.MatchedRoute `json:"matched_routes"`
	}
	if err := json.NewDecoder(response.Body).Decode(&body); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if body.Receiver != "pagerduty-database" {
		t.Fatalf("receiver = %q, want pagerduty-database", body.Receiver)
	}
	if len(body.MatchedRoutes) != 2 || body.MatchedRoutes[1].Depth != 1 || !body.MatchedRoutes[1].IsEffective {
		t.Fatalf("matched routes = %#v, want nested effective child", body.MatchedRoutes)
	}
	if body.MatchedRoutes[1].ResolvedReceiver != "pagerduty-database" {
		t.Fatalf("resolved receiver = %q, want pagerduty-database", body.MatchedRoutes[1].ResolvedReceiver)
	}
}

func TestHandleTestReturnsEmptyMatchedRouteArrayForRootFallback(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"config":{"original":"route:\n  receiver: default\nreceivers:\n- name: default\n"}}`))
	}))
	defer server.Close()

	h := &Handler{client: alertmanager.NewClient(server.URL, false)}
	request := httptest.NewRequest(http.MethodPost, "/test", bytes.NewBufferString(`{"labels":{"alertname":"unknown"}}`))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()

	h.HandleTest(response, request)

	var body map[string]json.RawMessage
	if err := json.NewDecoder(response.Body).Decode(&body); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if string(body["matched_routes"]) != "[]" {
		t.Fatalf("matched_routes = %s, want []", body["matched_routes"])
	}
}

func TestResultTemplateRendersMatchedRoutes(t *testing.T) {
	tmpl := loadTemplates(t)

	route := &alertmanager.Route{
		Receiver: "pagerduty-critical",
		Match:    map[string]string{"severity": "critical"},
	}

	data := resultData{
		Receiver: "pagerduty-critical",
		MatchedRoutes: []alertmanager.MatchedRoute{
			{
				Route:           route,
				Depth:           0,
				ParentReceivers: nil,
				IsSubroute:      false,
			},
		},
		MatchedReceivers: []string{"pagerduty-critical"},
		RouteSteps: []RouteStep{
			{
				Index:    1,
				Receiver: "pagerduty-critical",
				Match:    map[string]string{"severity": "critical"},
				IsFinal:  true,
			},
		},
		FinalMatch: MatchSummary{
			Match: map[string]string{"severity": "critical"},
		},
		Labels: map[string]string{"severity": "critical", "alertname": "HighCPU"},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "result.html", data); err != nil {
		t.Fatalf("result.html failed to render: %v", err)
	}

	// Spot-check that the receiver name appears in the output.
	if !bytes.Contains(buf.Bytes(), []byte("pagerduty-critical")) {
		t.Error("expected receiver name 'pagerduty-critical' in rendered output")
	}
}

// TestResultTemplateRendersSubroute verifies result.html renders correctly when
// a MatchedRoute carries subroute context (Depth > 0, ParentReceivers set).
func TestResultTemplateRendersSubroute(t *testing.T) {
	tmpl := loadTemplates(t)

	parentRoute := &alertmanager.Route{
		Receiver: "team-database",
		Match:    map[string]string{"team": "database"},
	}
	childRoute := &alertmanager.Route{
		Receiver: "pagerduty-database",
		Match:    map[string]string{"severity": "critical"},
	}

	data := resultData{
		Receiver: "pagerduty-database",
		MatchedRoutes: []alertmanager.MatchedRoute{
			{Route: parentRoute, Depth: 0, IsSubroute: false},
			{Route: childRoute, Depth: 1, ParentReceivers: []string{"team-database"}, IsSubroute: true},
		},
		MatchedReceivers: []string{"pagerduty-database"},
		RouteSteps: []RouteStep{
			{Index: 1, Receiver: "team-database", Match: map[string]string{"team": "database"}, IsEffective: false},
			{Index: 2, Receiver: "pagerduty-database", Match: map[string]string{"severity": "critical"},
				Depth: 1, ParentReceivers: []string{"team-database"}, IsSubroute: true, IsEffective: true, IsFinal: true},
		},
		FinalMatch: MatchSummary{Match: map[string]string{"severity": "critical"}},
		Labels:     map[string]string{"team": "database", "severity": "critical"},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "result.html", data); err != nil {
		t.Fatalf("result.html failed to render with subroute data: %v", err)
	}

	out := buf.Bytes()
	if !bytes.Contains(out, []byte("pagerduty-database")) {
		t.Error("expected 'pagerduty-database' in rendered output")
	}
	if !bytes.Contains(out, []byte("team-database")) {
		t.Error("expected parent 'team-database' in rendered output")
	}
	if bytes.Contains(out, []byte("Multiple receivers will be notified")) {
		t.Error("nested parent and child should not trigger multiple-receiver notice")
	}
	if !bytes.Contains(out, []byte("trace-trace-only-badge")) {
		t.Error("trace-only parent marker is missing")
	}
}

// TestResultTemplateRendersDefaultRoot verifies result.html renders correctly
// when no routes matched and the root default receiver is used.
func TestResultTemplateRendersDefaultRoot(t *testing.T) {
	tmpl := loadTemplates(t)

	data := resultData{
		Receiver:         "default",
		MatchedRoutes:    nil,
		MatchedReceivers: []string{"default"},
		DefaultRoot:      true,
		Labels:           map[string]string{"alertname": "Unknown"},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "result.html", data); err != nil {
		t.Fatalf("result.html failed to render with default root: %v", err)
	}
	output := buf.String()
	if !strings.Contains(output, "root receiver") || !strings.Contains(output, "result-default") {
		t.Fatalf("default root output = %q, want default notice and styling", output)
	}
}

func TestIndexTemplateIncludesShareLinkControls(t *testing.T) {
	tmpl := loadTemplates(t)
	data := struct {
		LabelSuggestions     []alertmanager.LabelSuggestion
		SampleAlerts         []alertmanager.SampleAlert
		Config               *alertmanager.Config
		AlertmanagerURL      string
		AlertmanagerNames    []string
		SelectedAlertmanager string
		ConnectionStatus     bool
		ConnectionError      string
		ConfigCachedAt       time.Time
		ConfigWasCached      bool
	}{}
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "index.html", data); err != nil {
		t.Fatalf("index.html failed to render: %v", err)
	}
	output := buf.String()
	if !strings.Contains(output, "Share link") {
		t.Fatal("share link control is missing")
	}
	if !strings.Contains(output, "loadSharedLabels") {
		t.Fatal("share link loading behavior is missing")
	}
}

func TestIndexTemplateIncludesRedesignControls(t *testing.T) {
	tmpl := loadTemplates(t)
	data := struct {
		LabelSuggestions     []alertmanager.LabelSuggestion
		SampleAlerts         []alertmanager.SampleAlert
		Config               *alertmanager.Config
		AlertmanagerURL      string
		AlertmanagerNames    []string
		SelectedAlertmanager string
		ConnectionStatus     bool
		ConnectionError      string
		ConfigCachedAt       time.Time
		ConfigWasCached      bool
	}{AlertmanagerURL: "http://localhost:9093", ConnectionStatus: true, ConfigCachedAt: time.Now()}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "index.html", data); err != nil {
		t.Fatalf("index.html failed to render: %v", err)
	}

	output := buf.String()
	for _, expected := range []string{
		`src="/static/htmx.min.js"`,
		`class="app-headerbar"`,
		`class="theme-switch"`,
		`aria-label="Test the alert route"`,
		`aria-live="polite"`,
		`textContent = key`,
	} {
		if !strings.Contains(output, expected) {
			t.Errorf("rendered index template does not contain %q", expected)
		}
	}
}

func TestResultTemplateIncludesRedesignHelp(t *testing.T) {
	tmpl := loadTemplates(t)
	data := resultData{
		Receiver: "pagerduty-database",
		MatchedRoutes: []alertmanager.MatchedRoute{
			{Route: &alertmanager.Route{Receiver: "team-database"}},
			{Route: &alertmanager.Route{Receiver: "pagerduty-database"}, Depth: 1, IsSubroute: true, IsEffective: true, ParentReceivers: []string{"team-database"}},
		},
		RouteSteps: []RouteStep{
			{Index: 1, Receiver: "team-database"},
			{Index: 2, Receiver: "pagerduty-database", Depth: 1, IsSubroute: true, IsEffective: true, ParentReceivers: []string{"team-database"}, IsFinal: true},
		},
		MatchedReceivers: []string{"team-database", "pagerduty-database"},
		Labels:           map[string]string{"team": "database"},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "result.html", data); err != nil {
		t.Fatalf("result.html failed to render: %v", err)
	}

	output := buf.String()
	for _, expected := range []string{
		`class="route-trace"`,
		`trace-final`,
		`trace-subroute`,
		`data-tooltip="Alertmanager sends the alert to this receiver."`,
		`Matched receivers (2)`,
		`Each receiver gets a copy.`,
	} {
		if !strings.Contains(output, expected) {
			t.Errorf("rendered result template does not contain %q", expected)
		}
	}
}
